#!/bin/bash

SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR"

docker build -t create_netcdf4_for_extract . # --no-cache

docker run --user $(id -u):$(id -g) \
           -v $(pwd)/data:/data:rw  \
           -w /data                 \
           create_netcdf4_for_extract
