version: '3'

services:

  icatdb:
    hostname: dbhost
    build:
        context: .
        dockerfile: Dockerfile.postgres
    networks:
        default:
            aliases:
                [ "dbhost" ]

  irodsprov:
    hostname: irodshost
    build:
        context: .
        dockerfile: Dockerfile.provider
        args:
          irods_vsn: ${irods_version}
    networks:
        default:
            aliases:
                [ "irodshost" ]
    cap_add:
        - SYS_PTRACE

  irodscons:
    hostname: consumer
    build:
        context: .
        dockerfile: Dockerfile.consumer
        args:
          irods_vsn: ${irods_version}
    networks:
        default:
            aliases:
                [ "consumer" ]
    depends_on:
     - irodsprov
    cap_add:
        - SYS_PTRACE


  cldbrowser:
    image: "diceunc/cloudbrowser:1.0.2.0-beta4"
    volumes:
     - ./irods-ext-cb:/etc/irods-ext:ro
    ports:
     - "9090:8080"
    depends_on:
     - irodsprov
     - icatdb

  metalnxdemo:
    hostname: metalnxhost
    image: "irods/metalnx:2.0.0"
    ports: 
     - "8080:8080"
    volumes:
     - ./irods-ext:/etc/irods-ext:ro
    networks:
        default:
            aliases:
             - metalnxhost
    depends_on:
     - irodsprov
     - icatdb
