version: '3'

services:

  icatdb:
    hostname: dbhost
    build:
        context: .
        dockerfile: Dockerfile.postgres
    networks:
        default:
            aliases:
                [ "dbhost" ]

  irodsprov:
    hostname: irodshost
    build:
        context: .
        dockerfile: Dockerfile.provider
        args:
          irods_vsn: ${irods_version}
    networks:
        default:
            aliases:
                [ "irodshost" ]
    cap_add:
        - SYS_PTRACE

  irodscons:
    hostname: consumer
    build:
        context: .
        dockerfile: Dockerfile.consumer
        args:
          irods_vsn: ${irods_version}
    networks:
        default:
            aliases:
                [ "consumer" ]
    depends_on:
     - irodsprov
    cap_add:
        - SYS_PTRACE
