FROM centos:7

RUN yum install -y wget vim wget less

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

RUN yum install -y postgresql-server

RUN su - postgres -c 'pg_ctl  initdb'

ADD start_pg.sh /

RUN chmod +x /*.sh

ADD pg_hba.conf postgresql.conf /

RUN cp /postgresql.conf /pg_hba.conf /var/lib/pgsql/data/.

EXPOSE 5432

CMD [ "/start_pg.sh" ]
